-- CreateEnum
CREATE TYPE "CoreNetworkType" AS ENUM ('EMERGENCY_FUND', 'RENT', 'WANTS_SANDBOX', 'INVESTMENTS', 'INSURANCE', 'CREDIT_BUFFER', 'PERSONAL_GOAL', 'SAVINGS_VAULT', 'CREDIT_CARD', 'UTILITIES', 'PAYCHECK');

-- AlterTable
ALTER TABLE "CoreNetwork" ADD COLUMN     "type" "CoreNetworkType";
